### ISSUE TITLE
프로젝트 피드백 - 작성자 : 손지수

### ISSUE THREAD

**Issue by lyle0101** [sxi8022/sp_prj_sample#1]
## Overview
- 가장 눈에 띄었던 건 코드가 아니라 실행사진이었던 것 같습니다. 저장소는 코드가 주인공이어야 하기 때문에 다음번에는 실행사진들을 폴더에 정리하거나 README.md에 첨부해주시는 방향으로 저장소를 관리해주시면 좋을 것 같습니다.
- Commit을 어느 정도 분리해서 나눠주셨지만 Commit 메세지에 통일성이 있었다면 더 좋았을 것 같습니다. 물론 이번 프로젝트는 협업을 하는 프로젝트가 아니었지만 Commit 메세지를 잘 쓰는 연습도 필요할 것으로 보입니다.
- .gitignore 파일이 존재하지 않아 .idea 폴더가 함께 Commit 된 것은 아쉽습니다. 다음에는 .gitignore 파일을 잘 작성해주시면 좋을 것 같습니다.
- VO(Value Object)와 Entity의 개념을 확실히 구분하지 못하고 계신걸로 보입니다. 관련해서 VO와 Entity가 어떻게 다른지 공부해보시면 좋을 것 같습니다.
- 사용하지 않는 코드는 특별한 이유가 있지 않는 한 주석 처리를 하는 것보다 삭제해주시는게 좋습니다.

코드 레벨에 대한 리뷰는 아래에 이어서 작성해두었습니다.

**Comment by lyle0101** [comment]
## Comment.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/vo/Comment.java#L12-L23

- 사용하지 않는 어노테이션을 삭제할 필요가 있어보입니다. 특히 @EntityListeners 어노테이션의 경우 Timestamped를 상속받으며 이미 적용되어 있는데 중복으로 선언되어 있습니다. 그 외에 @Builder, @AllArgsConstructor 어노테이션도 사용 여부를 확인해서 삭제가 필요하면 삭제해주시길 바랍니다.

**Comment by lyle0101** [comment]
## Post.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/vo/Post.java#L24-L29

- 이런 주석들이 바로 삭제해야 할 주석들입니다. 실제 현업에서는 코드를 공유하실 때 이런식의 필요없는 주석을 남겨놓으면 안됩니다. 같이 협업을 진행하는 동료에게 혼란을 줄 수 있기 때문입니다.

**Comment by lyle0101** [comment]
## UserController.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/controller/UserController.java#L23-L30

- 응답을 DTO로 만들지 않고 HashMap을 사용하신 이유가 궁금합니다. 또한 HashMap을 사용하시더라도 value의 타입에 Object를 사용하신건 지양해야 할 코드입니다. Object를 사용하면 어떤 타입의 객체든 들어갈 수 있기 때문에 정적 타입 언어의 이점을 모두 잃는 것이 됩니다.

**Comment by lyle0101** [comment]
## ExtException.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/exception/ExtException.java#L10-L12

- Http Status Code 중 400 에러는 HttpStatus.BAD_REQUEST에 해당합니다. 해당 코드를 작성하시기에 앞서 Http Status Code에 대한 충분한 이해가 필요해 보입니다.

**Comment by lyle0101** [comment]
## PostController.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/controller/PostController.java#L67-L68

- RESTful 하지 않은 API 입니다. REST API란 무엇인지 알고 사용하면 더 좋을 것 같습니다.
- 참고 링크 : https://meetup.nhncloud.com/posts/92

**Comment by lyle0101** [comment]
## PostService.java

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/service/PostService.java#L40-L49

- request에서 직접 User를 꺼내는 것이 아니라 controller 단에서 @AuthenticationPrincipal 어노테이션을 활용하여 User 객체를 얻어왔다면 더 좋을 것 같습니다.

https://github.com/sxi8022/sp_prj_sample/blob/ff3b4ee5b20d5914928e700b562f4ea4d68a8ffd/ExPost/src/main/java/com/spr/expost/service/PostService.java#L153-L154

- @Transactional 어노테이션에 대한 이해를 선행하고 사용하시면 좋을 것 같습니다.

**Comment by sxi8022** [comment]
리뷰 감사합니다.
